/**
 * Playwright Context — "The Gatherer"
 *
 * Ported from ai-pr-review/src/pw-context-worker.js.
 * Gathers Angular component context, docs, existing tests,
 * then delegates to generate + push.
 */

const { fetchWithRetry } = require("../utils/fetchWithRetry");
const { orgUrl, azureHeaders, retryOpts, AZURE_API_VERSION } = require("../lib/azurePr");
const { postPrComment } = require("../lib/prComments");
const { PLAYWRIGHT_TEST_BRANCH } = require("../lib/constants");
const { kvStore } = require("../lib/kvStore");
const { generateTests } = require("./playwrightGenerate");
const { pushFlow } = require("./playwrightPush");

const MAX_MD_CHARS = 24000;
const MAX_COMPONENT_FILES = 10;
const DOC_CACHE_TTL = 3600; // 1 hour

const MD_DOC_PATHS = [
  "/REPOSITORY_CONTEXT.md",
  "/PULSE_REFERENCE.md",
  "/CLAUDE.md",
];

// ─── Main Test Generation Flow ───────────────────────────────────────────────

async function runTestGeneration(payload, context) {
  const { prId, repoId, project, prTitle, fileChanges, dryRun } = payload;
  const headers = azureHeaders();

  try {
    context.log(`[PW-Context] Starting test generation for PR #${prId}${dryRun ? " (DRY RUN)" : ""}`);

    // 1. Identify Angular component files
    const componentFiles = identifyComponentFiles(fileChanges);
    if (componentFiles.length === 0) {
      context.log("[PW-Context] No Angular component files changed, skipping");
      return;
    }

    // 2. Fetch docs and existing test files in parallel
    const [mdDocs, existingFiles] = await Promise.all([
      fetchMdDocs(project, repoId, headers, context),
      fetchExistingTestFiles(project, repoId, componentFiles, headers, context),
    ]);

    // 3. Generate tests via AI
    context.log(`[PW-Context] Delegating AI generation (${componentFiles.length} components, ${mdDocs.length} docs)`);
    let generatedTests = null;
    try {
      generatedTests = await generateTests(componentFiles, mdDocs, existingFiles, prTitle, context);
    } catch (genErr) {
      context.log.error(`[PW-Context] Generation failed: ${genErr.message}`);
    }

    if (!generatedTests || generatedTests.length === 0) {
      context.log("[PW-Context] AI generated no tests");
      if (!dryRun) {
        await postPrComment(project, repoId, prId, headers,
          `## \ud83c\udfad Playwright Test Generation\n\n\u26a0\ufe0f AI could not generate tests for the changed components.\n\n### Changed Components Analyzed\n${componentFiles.map(f => "- `" + f.path + "`").join("\n")}\n\n---\n_Generated by DevOps AI Bot \u2014 Playwright Test Gen_`,
          context, "PW-Context");
      }
      return;
    }

    context.log(`[PW-Context] AI generated ${generatedTests.length} test files`);

    // Dry run: log and stop
    if (dryRun) {
      context.log("[PW-Context] DRY RUN \u2014 skipping push, pipeline, and PR comment");
      for (const t of generatedTests) {
        context.log(`[PW-Context] [DRY RUN] Would create: ${t.filePath} (${t.content.length} chars)`);
      }
      return;
    }

    // 4. Push + pipeline + PR comment
    await pushFlow({
      project, repoId, prId,
      generatedTests, componentFiles,
      docsCount: mdDocs.length,
    }, context);

    context.log(`[PW-Context] Test generation flow completed for PR #${prId}`);
  } catch (e) {
    context.log.error(`[PW-Context] Flow error: ${e.message}`);
    if (!dryRun) {
      try {
        await postPrComment(project, repoId, prId, headers,
          `## \ud83c\udfad Playwright Test Generation\n\n\u274c An error occurred:\n\`${e.message}\`\n\n---\n_Generated by DevOps AI Bot \u2014 Playwright Test Gen_`,
          context, "PW-Context");
      } catch (_postErr) { /* ignore */ }
    }
  }
}

// ─── Identify Angular Component Files ────────────────────────────────────────

function identifyComponentFiles(fileChanges) {
  const componentPatterns = /\.(component\.ts|component\.html|service\.ts|guard\.ts|interceptor\.ts|resolver\.ts|directive\.ts|pipe\.ts|module\.ts|routing\.ts)$/i;
  return fileChanges
    .filter(fc => componentPatterns.test(fc.path))
    .slice(0, MAX_COMPONENT_FILES)
    .map(fc => {
      const pathParts = fc.path.split("/");
      const fileName = pathParts[pathParts.length - 1];
      const stem = fileName.replace(/\.(component|service|guard|interceptor|resolver|directive|pipe|module|routing)\.(ts|html)$/i, "");
      return { path: fc.path, stem, diff: fc.diff, isAdd: fc.isAdd };
    });
}

// ─── Fetch .md Documentation from Test Branch ────────────────────────────────

async function fetchMdDocs(project, repoId, headers, context) {
  const ORG = orgUrl();
  const results = await Promise.allSettled(
    MD_DOC_PATHS.map(async (docPath) => {
      // Try cache first
      try {
        const cached = kvStore.get(`doc:${docPath}`);
        if (cached) return { path: docPath, content: cached };
      } catch (_cacheReadErr) { /* ignore */ }

      const contentUrl = `${ORG}/${project}/_apis/git/repositories/${repoId}/items?path=${encodeURIComponent(docPath)}&versionDescriptor.version=${encodeURIComponent(PLAYWRIGHT_TEST_BRANCH)}&versionDescriptor.versionType=branch&includeContent=true&api-version=${AZURE_API_VERSION}`;
      const contentRes = await fetchWithRetry(contentUrl, { headers }, retryOpts(context, "PW-Context"));
      if (!contentRes.ok) return null;
      let content = await contentRes.text();
      if (content.length > MAX_MD_CHARS) content = content.substring(0, MAX_MD_CHARS) + "\n...(truncated)";

      // Cache
      try { kvStore.put(`doc:${docPath}`, content, { expirationTtl: DOC_CACHE_TTL }); } catch (_cacheWriteErr) { /* ignore */ }

      return { path: docPath, content };
    })
  );

  return results.filter(r => r.status === "fulfilled" && r.value !== null).map(r => r.value);
}

// ─── Fetch Existing Test Files from Test Branch ──────────────────────────────

async function fetchExistingTestFiles(project, repoId, componentFiles, headers, context) {
  const ORG = orgUrl();
  const pathsToCheck = ["/tests/fixtures/actionsFixture.ts"];
  const stems = [...new Set(componentFiles.map(f => f.stem))];
  for (const stem of stems) {
    pathsToCheck.push(`/tests/components/${stem}/${stem}Actions.ts`);
    pathsToCheck.push(`/tests/components/${stem}/${stem}.spec.ts`);
  }

  const results = await Promise.allSettled(
    pathsToCheck.map(async (filePath) => {
      const contentUrl = `${ORG}/${project}/_apis/git/repositories/${repoId}/items?path=${encodeURIComponent(filePath)}&versionDescriptor.version=${encodeURIComponent(PLAYWRIGHT_TEST_BRANCH)}&versionDescriptor.versionType=branch&includeContent=true&api-version=${AZURE_API_VERSION}`;
      const contentRes = await fetchWithRetry(contentUrl, { headers }, retryOpts(context, "PW-Context"));
      if (!contentRes.ok) return null;
      const fullContent = await contentRes.text();
      let promptContent = fullContent;
      if (promptContent.length > 4000) promptContent = promptContent.substring(0, 4000) + "\n...(truncated)";
      return { path: filePath, content: promptContent, fullContent };
    })
  );

  return results.filter(r => r.status === "fulfilled" && r.value !== null).map(r => r.value);
}

module.exports = { runTestGeneration };
