/**
 * Playwright Push — "The Committer"
 *
 * Ported from ai-pr-review/src/pw-push-worker.js.
 * Pushes generated test files to git, triggers pipeline, posts PR comment.
 */

const { fetchWithRetry } = require("../utils/fetchWithRetry");
const { orgUrl, azureHeaders, retryOpts, AZURE_API_VERSION } = require("../lib/azurePr");
const { postPrComment } = require("../lib/prComments");
const { PLAYWRIGHT_TEST_BRANCH } = require("../lib/constants");

// ─── Main Push Flow ──────────────────────────────────────────────────────────

async function pushFlow(payload, context) {
  const { project, repoId, prId, generatedTests, componentFiles, docsCount, errorMsg } = payload;
  const pipelineId = parseInt(process.env.PIPELINE_ID || "88", 10);
  const headers = azureHeaders();

  try {
    const pushResult = await pushTests(project, repoId, generatedTests, prId, headers, context);
    context.log(`[PW-Push] Push result: ${pushResult.success ? "success" : "failed"}`);

    let pipelineTriggered = false;
    if (pushResult.success) {
      pipelineTriggered = await triggerPipeline(project, headers, context, pipelineId);
    }

    const comment = buildComment(generatedTests, componentFiles || [], docsCount || 0, errorMsg || null, pushResult.success, pipelineTriggered, pipelineId);
    await postPrComment(project, repoId, prId, headers, comment, context, "PW-Push");
  } catch (e) {
    context.log.error(`[PW-Push] Flow error: ${e.message}`);
    try {
      await postPrComment(project, repoId, prId, headers,
        `## \ud83c\udfad Playwright Test Generation\n\n\u274c An error occurred during push:\n\`${e.message}\`\n\n---\n_Generated by DevOps AI Bot \u2014 Playwright Push_`,
        context, "PW-Push");
    } catch (commentErr) {
      context.log.error(`[PW-Push] Could not post error comment: ${commentErr.message}`);
    }
  }
}

// ─── Push Tests to Branch ────────────────────────────────────────────────────

async function pushTests(project, repoId, generatedTests, prId, headers, context) {
  const ORG = orgUrl();
  try {
    // 1. Get branch tip ref
    const refsUrl = `${ORG}/${project}/_apis/git/repositories/${repoId}/refs?filter=heads/${PLAYWRIGHT_TEST_BRANCH}&api-version=${AZURE_API_VERSION}`;
    const refsRes = await fetchWithRetry(refsUrl, { headers }, retryOpts(context, "PW-Push"));
    if (!refsRes.ok) return { success: false, message: `Failed to get branch ref: ${refsRes.status}` };

    const refsData = await refsRes.json();
    const branchRef = (refsData.value || []).find(r => r.name === `refs/heads/${PLAYWRIGHT_TEST_BRANCH}`);
    if (!branchRef) return { success: false, message: `Branch ${PLAYWRIGHT_TEST_BRANCH} not found` };

    const oldObjectId = branchRef.objectId;

    // 2. Check which files already exist (parallel)
    const existChecks = await Promise.allSettled(
      generatedTests.map(async (test) => {
        const checkUrl = `${ORG}/${project}/_apis/git/repositories/${repoId}/items?path=${encodeURIComponent("/" + test.filePath)}&versionDescriptor.version=${encodeURIComponent(PLAYWRIGHT_TEST_BRANCH)}&versionDescriptor.versionType=branch&api-version=${AZURE_API_VERSION}`;
        const checkRes = await fetchWithRetry(checkUrl, { headers, method: "HEAD" }, { maxRetries: 1, timeoutMs: 5000 });
        return { test, exists: checkRes.ok };
      })
    );

    const changes = existChecks
      .filter(r => r.status === "fulfilled")
      .map(r => {
        const { test, exists } = r.value;
        return {
          changeType: exists ? "edit" : "add",
          item: { path: "/" + test.filePath },
          newContent: { content: test.content, contentType: "rawtext" },
        };
      });

    // 3. Push all files in a single commit
    const pushUrl = `${ORG}/${project}/_apis/git/repositories/${repoId}/pushes?api-version=${AZURE_API_VERSION}`;
    const pushBody = {
      refUpdates: [{ name: `refs/heads/${PLAYWRIGHT_TEST_BRANCH}`, oldObjectId }],
      commits: [{ comment: `[AI] Playwright tests for PR #${prId}`, changes }],
    };

    const pushRes = await fetchWithRetry(
      pushUrl,
      {
        method: "POST",
        headers: { ...headers, "Content-Type": "application/json" },
        body: JSON.stringify(pushBody),
      },
      retryOpts(context, "PW-Push")
    );

    if (pushRes.ok) return { success: true, message: "Tests pushed successfully" };
    const errText = await pushRes.text();
    return { success: false, message: `Push failed: ${pushRes.status} ${errText}` };
  } catch (e) {
    return { success: false, message: `Push error: ${e.message}` };
  }
}

// ─── Trigger Pipeline ────────────────────────────────────────────────────────

async function triggerPipeline(project, headers, context, pipelineId) {
  const ORG = orgUrl();
  try {
    const pipelineUrl = `${ORG}/${project}/_apis/pipelines/${pipelineId}/runs?api-version=${AZURE_API_VERSION}`;
    const pipelineBody = {
      resources: { repositories: { self: { refName: `refs/heads/${PLAYWRIGHT_TEST_BRANCH}` } } },
    };

    const res = await fetchWithRetry(
      pipelineUrl,
      {
        method: "POST",
        headers: { ...headers, "Content-Type": "application/json" },
        body: JSON.stringify(pipelineBody),
      },
      retryOpts(context, "PW-Push")
    );

    if (res.ok) {
      const data = await res.json();
      context.log(`[PW-Push] Pipeline ${pipelineId} triggered, run ID: ${data.id || "unknown"}`);
      return true;
    }
    context.log.error(`[PW-Push] Pipeline trigger failed: ${res.status}`);
    return false;
  } catch (e) {
    context.log.error(`[PW-Push] Pipeline trigger error: ${e.message}`);
    return false;
  }
}

// ─── Build PR Comment ────────────────────────────────────────────────────────

function buildComment(generatedTests, componentFiles, docsCount, errorMsg, pushSuccess, pipelineTriggered, pipelineId) {
  const body = [`## \ud83c\udfad Playwright Test Generation`, ``];
  if (errorMsg) {
    body.push(`\u26a0\ufe0f ${errorMsg}`, ``);
  } else {
    body.push(`Generated **${generatedTests.length}** test file(s) using **${docsCount}** documentation file(s) as context.`, ``);
    if (pushSuccess) {
      body.push(`\u2705 Tests pushed to \`${PLAYWRIGHT_TEST_BRANCH}\``);
      body.push(pipelineTriggered ? `\u2705 Pipeline #${pipelineId} triggered` : `\u26a0\ufe0f Pipeline trigger failed \u2014 run manually if needed`);
    } else {
      body.push(`\u274c Could not push tests to branch \u2014 see logs for details`);
    }
    body.push(``);
    if (generatedTests.length > 0) {
      body.push(`### Generated Test Files`);
      for (const t of generatedTests) body.push(`- \`${t.filePath}\``);
      body.push(``);
    }
  }
  if (componentFiles.length > 0) {
    body.push(`### Changed Components Analyzed`);
    for (const f of componentFiles) body.push(`- \`${f.path}\``);
    body.push(``);
  }
  body.push(`---`, `_Generated by DevOps AI Bot \u2014 Playwright Test Gen_`);
  return body.join("\n");
}

module.exports = { pushFlow };
