const { callAI } = require("../services/aiService");
const {
  extractPullRequestDataFromWebhook,
  postCommentToPullRequest,
} = require("../services/azureDevopsService");
const {
  getSystemPrompt,
  buildUserMessage,
} = require("../prompts/releaseNotesPrompt");

/**
 * Generates release notes from a merged pull request using AI and posts
 * the result as a comment thread on the PR in Azure DevOps.
 *
 * @param {object} payload - The raw Azure DevOps webhook body.
 * @param {object} context - Azure Function context.
 * @returns {object}         The AI release-notes result.
 */
async function generateReleaseNotes(payload, context) {
  context.log("Release Notes Generator - Start.");

  // 1. Extract PR data.
  const prData = extractPullRequestDataFromWebhook(payload);
  context.log(
    "PR #" + prData.pullRequestId + ": \"" + prData.title + "\" (" + prData.repositoryName + ")"
  );

  // 2. Call the AI service.
  const systemPrompt = getSystemPrompt();
  const userMessage = buildUserMessage(prData);
  const releaseNotes = await callAI(systemPrompt, userMessage, context);

  context.log("AI release notes generated.");
  context.log(JSON.stringify(releaseNotes, null, 2));

  // 3. Format and post.
  const comment = formatComment(releaseNotes);

  if (prData.pullRequestId && prData.project && prData.repositoryId) {
    await postCommentToPullRequest(
      prData.project,
      prData.repositoryId,
      prData.pullRequestId,
      comment,
      context
    );
  } else {
    context.log.warn(
      "Missing PR ID, project, or repository ID - skipping comment post."
    );
  }

  return {
    handler: "releaseNotesGenerator",
    pullRequestId: prData.pullRequestId,
    releaseNotes: releaseNotes,
  };
}

/**
 * Formats the AI release notes into a markdown comment for Azure DevOps.
 */
function formatComment(notes) {
  var technical =
    notes.technicalReleaseNotes || "No technical notes generated.";
  var customerFriendly =
    notes.customerFriendlyReleaseNotes || "No customer-facing notes generated.";

  var changes =
    Array.isArray(notes.listOfChanges) && notes.listOfChanges.length > 0
      ? notes.listOfChanges.map(function (c) { return "- " + c; }).join("\n")
      : "- No changes listed.";

  return "## Release Notes\n\n" +
    "### Technical Release Notes\n" +
    technical + "\n\n" +
    "### Customer-Friendly Release Notes\n" +
    customerFriendly + "\n\n" +
    "### List of Changes\n" +
    changes + "\n\n" +
    "---\n" +
    "*Generated by DevOps AI Bot*";
}

module.exports = { generateReleaseNotes };
