const { createHandler } = require("../utils/handlerFactory");
const {
  extractPullRequestDataFromWebhook,
  postCommentToPullRequest,
} = require("../services/azureDevopsService");
const promptModule = require("../prompts/releaseNotesPrompt");

/**
 * Formats the AI release notes into a markdown comment for Azure DevOps.
 * (PR comment threads support markdown.)
 */
function formatComment(notes) {
  const technical =
    notes.technicalReleaseNotes || "No technical notes generated.";
  const customerFriendly =
    notes.customerFriendlyReleaseNotes || "No customer-facing notes generated.";

  const changes =
    Array.isArray(notes.listOfChanges) && notes.listOfChanges.length > 0
      ? notes.listOfChanges.map((c) => `- ${c}`).join("\n")
      : "- No changes listed.";

  return (
    "## Release Notes\n\n" +
    "### Technical Release Notes\n" +
    `${technical}\n\n` +
    "### Customer-Friendly Release Notes\n" +
    `${customerFriendly}\n\n` +
    "### List of Changes\n" +
    `${changes}\n\n` +
    "---\n" +
    "*Generated by DevOps AI Bot*"
  );
}

const generateReleaseNotes = createHandler({
  name: "Release Notes Generator",
  extract: extractPullRequestDataFromWebhook,
  logExtracted: (prData, context) => {
    context.log(
      `PR #${prData.pullRequestId}: "${prData.title}" (${prData.repositoryName})`
    );
  },
  promptModule,
  formatComment,
  postComment: async (prData, comment, context) => {
    if (prData.pullRequestId && prData.project && prData.repositoryId) {
      await postCommentToPullRequest(
        prData.project,
        prData.repositoryId,
        prData.pullRequestId,
        comment,
        context
      );
    } else {
      context.log.warn("Missing PR ID, project, or repository ID - skipping comment post.");
    }
  },
  buildResult: (prData, releaseNotes) => ({
    handler: "releaseNotesGenerator",
    pullRequestId: prData.pullRequestId,
    releaseNotes,
  }),
});

module.exports = { generateReleaseNotes };
