const { callAI } = require("../services/aiService");
const {
  extractWorkItemDataFromWebhook,
  postCommentToWorkItem,
} = require("../services/azureDevopsService");
const {
  getSystemPrompt,
  buildUserMessage,
} = require("../prompts/analyzeTicketPrompt");

/**
 * Analyses a newly created work item using AI and posts the results
 * as a comment back to Azure DevOps.
 *
 * @param {object} payload - The raw Azure DevOps webhook body.
 * @param {object} context - Azure Function context.
 * @returns {object}         The AI analysis result.
 */
async function analyzeTicket(payload, context) {
  context.log("Ticket Analyzer - Start.");

  // 1. Extract work-item data from the webhook payload.
  const workItem = extractWorkItemDataFromWebhook(payload);
  context.log(
    "Work item #" + workItem.id + ": \"" + workItem.title + "\" (" + workItem.workItemType + ")"
  );

  // 2. Build prompts and call the AI service.
  const systemPrompt = getSystemPrompt();
  const userMessage = buildUserMessage(workItem);
  const analysis = await callAI(systemPrompt, userMessage, context);

  context.log("AI analysis complete.");
  context.log(JSON.stringify(analysis, null, 2));

  // 3. Format and post the comment.
  const comment = formatComment(analysis);

  if (workItem.id && workItem.project) {
    await postCommentToWorkItem(workItem.project, workItem.id, comment, context);
  } else {
    context.log.warn(
      "Missing work-item ID or project - skipping comment post."
    );
  }

  return { handler: "ticketAnalyzer", workItemId: workItem.id, analysis: analysis };
}

/**
 * Formats the AI analysis into an HTML comment suitable for Azure DevOps.
 */
function formatComment(analysis) {
  var score = analysis.qualityScore != null ? analysis.qualityScore : "N/A";
  var missing =
    Array.isArray(analysis.missingInformation) &&
    analysis.missingInformation.length > 0
      ? analysis.missingInformation.map(function (m) { return "<li>" + m + "</li>"; }).join("")
      : "<li>None identified</li>";

  var tooLarge = analysis.isTooLarge ? "Yes" : "No";
  var shouldSplit = analysis.shouldSplit ? "Yes" : "No";
  var improvements = analysis.suggestedImprovements || "No suggestions.";

  return "<h3>&#129302; AI Ticket Analysis</h3>\n" +
    "<table>\n" +
    "  <tr><td><b>Quality Score</b></td><td>" + score + " / 10</td></tr>\n" +
    "  <tr><td><b>Too Large?</b></td><td>" + tooLarge + "</td></tr>\n" +
    "  <tr><td><b>Should Split?</b></td><td>" + shouldSplit + "</td></tr>\n" +
    "</table>\n\n" +
    "<h4>Missing Information</h4>\n" +
    "<ul>" + missing + "</ul>\n\n" +
    "<h4>Suggested Improvements</h4>\n" +
    "<p>" + improvements + "</p>\n\n" +
    "<hr/>\n" +
    "<em>Generated by DevOps AI Bot</em>";
}

module.exports = { analyzeTicket };
