const { createHandler } = require("../utils/handlerFactory");
const { escapeHtml } = require("../utils/htmlEscape");
const { coerceNumber, coerceString, coerceStringArray } = require("../utils/validateAIResponse");
const {
  extractWorkItemDataFromWebhook,
  postCommentToWorkItem,
} = require("../services/azureDevopsService");
const promptModule = require("../prompts/analyzeTicketPrompt");

/**
 * Formats the AI analysis into an HTML comment suitable for Azure DevOps.
 * (Work item comments support HTML.)
 */
function formatComment(analysis) {
  const score = coerceNumber(analysis.qualityScore, 0, 10, null);
  const scoreDisplay = score !== null ? escapeHtml(score) : "N/A";

  const missingItems = coerceStringArray(analysis.missingInformation);
  const missing =
    missingItems.length > 0
      ? missingItems.map((m) => `<li>${escapeHtml(m)}</li>`).join("")
      : "<li>None identified</li>";

  const tooLarge = analysis.isTooLarge ? "Yes" : "No";
  const shouldSplit = analysis.shouldSplit ? "Yes" : "No";
  const improvements = escapeHtml(coerceString(analysis.suggestedImprovements, "No suggestions."));

  return (
    "<h3>&#129302; AI Ticket Analysis</h3>\n" +
    "<table>\n" +
    `  <tr><td><b>Quality Score</b></td><td>${scoreDisplay} / 10</td></tr>\n` +
    `  <tr><td><b>Too Large?</b></td><td>${tooLarge}</td></tr>\n` +
    `  <tr><td><b>Should Split?</b></td><td>${shouldSplit}</td></tr>\n` +
    "</table>\n\n" +
    "<h4>Missing Information</h4>\n" +
    `<ul>${missing}</ul>\n\n` +
    "<h4>Suggested Improvements</h4>\n" +
    `<p>${improvements}</p>\n\n` +
    "<hr/>\n" +
    "<em>Generated by DevOps AI Bot</em>"
  );
}

const analyzeTicket = createHandler({
  name: "Ticket Analyzer",
  extract: extractWorkItemDataFromWebhook,
  logExtracted: (workItem, context) => {
    context.log(
      `Work item #${workItem.id}: "${workItem.title}" (${workItem.workItemType})`
    );
  },
  promptModule,
  formatComment,
  postComment: async (workItem, comment, context) => {
    if (workItem.id && workItem.project) {
      await postCommentToWorkItem(workItem.project, workItem.id, comment, context);
    } else {
      context.log.warn("Missing work-item ID or project - skipping comment post.");
    }
  },
  buildResult: (workItem, analysis) => ({
    handler: "ticketAnalyzer",
    workItemId: workItem.id,
    analysis,
  }),
});

module.exports = { analyzeTicket, formatComment };
