const { callAI } = require("../services/aiService");
const {
  extractWorkItemDataFromWebhook,
  postCommentToWorkItem,
} = require("../services/azureDevopsService");
const {
  getSystemPrompt,
  buildUserMessage,
} = require("../prompts/estimateTimePrompt");

/**
 * Estimates time and complexity for a work item using AI and posts
 * the results as a comment in Azure DevOps.
 *
 * @param {object} payload - The raw Azure DevOps webhook body.
 * @param {object} context - Azure Function context.
 * @returns {object}         The AI estimation result.
 */
async function estimateTime(payload, context) {
  context.log("Time Estimator - Start.");

  // 1. Extract work-item data.
  const workItem = extractWorkItemDataFromWebhook(payload);
  context.log(
    "Work item #" + workItem.id + ": \"" + workItem.title + "\" (" + workItem.workItemType + ")"
  );

  // 2. Call the AI service.
  const systemPrompt = getSystemPrompt();
  const userMessage = buildUserMessage(workItem);
  const estimation = await callAI(systemPrompt, userMessage, context);

  context.log("AI estimation complete.");
  context.log(JSON.stringify(estimation, null, 2));

  // 3. Format and post.
  const comment = formatComment(estimation);

  if (workItem.id && workItem.project) {
    await postCommentToWorkItem(workItem.project, workItem.id, comment, context);
  } else {
    context.log.warn(
      "Missing work-item ID or project - skipping comment post."
    );
  }

  return { handler: "timeEstimator", workItemId: workItem.id, estimation: estimation };
}

/**
 * Formats the AI estimation into an HTML comment suitable for Azure DevOps.
 */
function formatComment(estimation) {
  var complexity = estimation.complexity || "N/A";
  var risk = estimation.riskLevel || "N/A";
  var reasoning = estimation.reasoning || "No reasoning provided.";

  var timeRange = "N/A";
  if (estimation.estimatedTimeInDays) {
    var min = estimation.estimatedTimeInDays.min != null ? estimation.estimatedTimeInDays.min : "?";
    var max = estimation.estimatedTimeInDays.max != null ? estimation.estimatedTimeInDays.max : "?";
    timeRange = min + " - " + max + " days";
  }

  var complexityIcon =
    complexity === "low" ? "[LOW]" : complexity === "medium" ? "[MEDIUM]" : "[HIGH]";

  var riskIcon =
    risk === "low" ? "[LOW]" : risk === "medium" ? "[MEDIUM]" : "[HIGH]";

  return "<h3>&#9202; AI Time Estimation</h3>\n" +
    "<table>\n" +
    "  <tr><td><b>Estimated Complexity</b></td><td>" + complexityIcon + " " + capitalize(complexity) + "</td></tr>\n" +
    "  <tr><td><b>Estimated Time</b></td><td>" + timeRange + "</td></tr>\n" +
    "  <tr><td><b>Risk Level</b></td><td>" + riskIcon + " " + capitalize(risk) + "</td></tr>\n" +
    "</table>\n\n" +
    "<h4>Reasoning</h4>\n" +
    "<p>" + reasoning + "</p>\n\n" +
    "<hr/>\n" +
    "<em>Generated by DevOps AI Bot</em>";
}

function capitalize(str) {
  if (!str) return str;
  return str.charAt(0).toUpperCase() + str.slice(1);
}

module.exports = { estimateTime };
