const { createHandler } = require("../utils/handlerFactory");
const { escapeHtml } = require("../utils/htmlEscape");
const { capitalize } = require("../utils/capitalize");
const { coerceEnum, coerceString } = require("../utils/validateAIResponse");
const {
  extractWorkItemDataFromWebhook,
  postCommentToWorkItem,
} = require("../services/azureDevopsService");
const promptModule = require("../prompts/estimateTimePrompt");

/**
 * Formats the AI estimation into an HTML comment suitable for Azure DevOps.
 * (Work item comments support HTML.)
 */
function formatComment(estimation) {
  const complexity = coerceEnum(estimation.complexity, ["low", "medium", "high"], "N/A");
  const risk = coerceEnum(estimation.riskLevel, ["low", "medium", "high"], "N/A");
  const reasoning = escapeHtml(coerceString(estimation.reasoning, "No reasoning provided."));

  let timeRange = "N/A";
  if (estimation.estimatedTimeInDays) {
    const min = estimation.estimatedTimeInDays.min !== null && estimation.estimatedTimeInDays.min !== undefined ? estimation.estimatedTimeInDays.min : "?";
    const max = estimation.estimatedTimeInDays.max !== null && estimation.estimatedTimeInDays.max !== undefined ? estimation.estimatedTimeInDays.max : "?";
    timeRange = `${min} - ${max} days`;
  }

  const complexityIcon =
    complexity === "low" ? "[LOW]" : complexity === "medium" ? "[MEDIUM]" : "[HIGH]";

  const riskIcon =
    risk === "low" ? "[LOW]" : risk === "medium" ? "[MEDIUM]" : "[HIGH]";

  return (
    "<h3>&#9202; AI Time Estimation</h3>\n" +
    "<table>\n" +
    `  <tr><td><b>Estimated Complexity</b></td><td>${complexityIcon} ${escapeHtml(capitalize(complexity))}</td></tr>\n` +
    `  <tr><td><b>Estimated Time</b></td><td>${escapeHtml(timeRange)}</td></tr>\n` +
    `  <tr><td><b>Risk Level</b></td><td>${riskIcon} ${escapeHtml(capitalize(risk))}</td></tr>\n` +
    "</table>\n\n" +
    "<h4>Reasoning</h4>\n" +
    `<p>${reasoning}</p>\n\n` +
    "<hr/>\n" +
    "<em>Generated by DevOps AI Bot</em>"
  );
}

const estimateTime = createHandler({
  name: "Time Estimator",
  extract: extractWorkItemDataFromWebhook,
  logExtracted: (workItem, context) => {
    context.log(
      `Work item #${workItem.id}: "${workItem.title}" (${workItem.workItemType})`
    );
  },
  promptModule,
  formatComment,
  postComment: async (workItem, comment, context) => {
    if (workItem.id && workItem.project) {
      await postCommentToWorkItem(workItem.project, workItem.id, comment, context);
    } else {
      context.log.warn("Missing work-item ID or project - skipping comment post.");
    }
  },
  buildResult: (workItem, estimation) => ({
    handler: "timeEstimator",
    workItemId: workItem.id,
    estimation,
  }),
});

module.exports = { estimateTime, formatComment };
