const { callAI } = require("../services/aiService");
const { escapeHtml } = require("./htmlEscape");

/**
 * Creates a webhook handler function from a configuration object.
 *
 * This eliminates the duplicated extract → prompt → AI → format → post pattern
 * across all feature handlers.
 *
 * If the AI returns unparseable JSON (indicated by a `rawResponse` key), the
 * handler falls back to a generic HTML comment containing the raw text instead
 * of passing malformed data to formatComment().
 *
 * @param {object} config
 * @param {string}   config.name            - Handler name for logging and response (e.g. "ticketAnalyzer").
 * @param {Function} config.extract         - (payload) => extracted data object.
 * @param {Function} config.logExtracted    - (data, context) => void — logs the extracted data.
 * @param {object}   config.promptModule    - Must export getSystemPrompt() and buildUserMessage(data).
 * @param {Function} config.formatComment   - (aiResult) => string — formats AI output for posting.
 * @param {Function} config.postComment     - (data, comment, context) => Promise — posts the comment.
 * @param {Function} config.buildResult     - (data, aiResult) => object — builds the return value.
 * @returns {Function} async (payload, context) => result
 */
function createHandler(config) {
  const {
    name,
    extract,
    logExtracted,
    promptModule,
    formatComment,
    postComment,
    buildResult,
  } = config;

  return async function handler(payload, context) {
    context.log(`${name} - Start.`);

    // 1. Extract data from the webhook payload.
    const data = extract(payload);
    logExtracted(data, context);

    // 2. Build prompts and call the AI service.
    const systemPrompt = promptModule.getSystemPrompt();
    const userMessage = promptModule.buildUserMessage(data);
    const aiResult = await callAI(systemPrompt, userMessage, context);

    context.log(`${name} - AI processing complete.`);

    // 3. Format and post the comment.
    //    If the AI returned raw (non-JSON) text, use a generic fallback comment.
    let comment;
    if (aiResult.rawResponse) {
      context.log.warn(
        `${name} - AI did not return structured JSON. Using raw response fallback.`
      );
      comment =
        `<h3>${escapeHtml(name)} (AI Raw Response)</h3>\n` +
        `<pre>${escapeHtml(aiResult.rawResponse)}</pre>\n` +
        "<hr/>\n" +
        "<em>Generated by DevOps AI Bot (unstructured response)</em>";
    } else {
      comment = formatComment(aiResult);
    }

    // Post the comment but tolerate failures — the AI analysis is still valuable
    // even if we can't post it back to Azure DevOps.
    try {
      await postComment(data, comment, context);
    } catch (postErr) {
      context.log.error(
        `${name} - Failed to post comment: ${postErr.message}. Continuing with result.`
      );
    }

    return buildResult(data, aiResult);
  };
}

module.exports = { createHandler };
